# Generated by Django 2.2.1 on 2019-05-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Без названия', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
